export enum COMPLAINT_STATUS {
  PENDING = 'pending', // Đã gửi
  ACCEPTED = 'accepted', // Đã nhận
  DECLINED = 'declined', // Không nhận
  APPROVED = 'approved', // Đã duyệt
  REJECTED = 'rejected', // Không duyệt
  CONTRACT_REQUESTED = 'contract_requested', // Cần làm hợp đồng
  IN_PROGRESS = 'in_progress', // Đang xử lý
  CLOSED = 'closed', // Đóng hồ sơ
  RESOLVED = 'resolved', // Đã hoàn thành
}

export const COMPLAINT_STATUS_COLOR = {
  [COMPLAINT_STATUS.PENDING]: '#0f71e5',
  [COMPLAINT_STATUS.ACCEPTED]: '#0f71e5',
  [COMPLAINT_STATUS.DECLINED]: '#e71414',
  [COMPLAINT_STATUS.APPROVED]: '#008a0e',
  [COMPLAINT_STATUS.REJECTED]: '#e71414',
  [COMPLAINT_STATUS.CONTRACT_REQUESTED]: '#d916a8',
  [COMPLAINT_STATUS.IN_PROGRESS]: '#0f71e5',
  [COMPLAINT_STATUS.RESOLVED]: '#008573',
  [COMPLAINT_STATUS.CLOSED]: '#e71414',
}

export const COMPLAINT_STATUS_BACKGROUND_COLOR = {
  [COMPLAINT_STATUS.PENDING]: '#EBF1FF',
  [COMPLAINT_STATUS.ACCEPTED]: '#EBF1FF',
  [COMPLAINT_STATUS.DECLINED]: '#FFE6E6',
  [COMPLAINT_STATUS.APPROVED]: '#E6F9F0',
  [COMPLAINT_STATUS.REJECTED]: '#FFE6E6',
  [COMPLAINT_STATUS.CONTRACT_REQUESTED]: '#ee98fb',
  [COMPLAINT_STATUS.IN_PROGRESS]: '#EBF1FF',
  [COMPLAINT_STATUS.RESOLVED]: '#b2dfdb',
  [COMPLAINT_STATUS.CLOSED]: '#FFE6E6',
}

export const COMPLAINT_STATUS_LABEL = {
  [COMPLAINT_STATUS.PENDING]: 'Đã gửi',
  [COMPLAINT_STATUS.ACCEPTED]: 'Đã nhận',
  [COMPLAINT_STATUS.DECLINED]: 'Không nhận',
  [COMPLAINT_STATUS.APPROVED]: 'Đã duyệt',
  [COMPLAINT_STATUS.REJECTED]: 'Không duyệt',
  [COMPLAINT_STATUS.CONTRACT_REQUESTED]: 'Cần làm hợp đồng',
  [COMPLAINT_STATUS.IN_PROGRESS]: 'Đang xử lý',
  [COMPLAINT_STATUS.RESOLVED]: 'Đã hoàn thành',
  [COMPLAINT_STATUS.CLOSED]: 'Đóng hồ sơ',
}

export enum CANCEL_REQUEST_STATUS {
  PENDING = 'pending',
  APPROVED = 'approved',
  REJECTED = 'rejected',
}

export const CANCEL_REQUEST_STATUS_LABEL = {
  [COMPLAINT_STATUS.PENDING]: 'Đang huỷ',
  [COMPLAINT_STATUS.APPROVED]: 'Đã huỷ',
  [COMPLAINT_STATUS.REJECTED]: 'Huỷ thất bại',
}

export const CANCEL_REQUEST_STATUS_COLOR = {
  [COMPLAINT_STATUS.PENDING]: '#e71414',
  [COMPLAINT_STATUS.APPROVED]: '#e71414',
  [COMPLAINT_STATUS.REJECTED]: '#e71414',
}

export const CANCEL_REQUEST_STATUS_BACKGROUND_COLOR = {
  [COMPLAINT_STATUS.PENDING]: '#FFE6E6',
  [COMPLAINT_STATUS.APPROVED]: '#FFE6E6',
  [COMPLAINT_STATUS.REJECTED]: '#FFE6E6',
}