version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/infofx-website/
    overwrite: purge
file_exists_behavior: OVERWRITE

hooks:
  ApplicationStart:
    - location: start.sh
      run_as: ubuntu
      timeout: 300
